{{ if  .Values.extraEnvVars -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "directus.fullname" . }}-extra-environment-variables
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "directus.labels" . | nindent 4 }}
data:
{{- range .Values.extraEnvVars }}
  {{ .name }}: {{ .value | quote }}
{{- end }}
{{- end }}